#!/data/data/com.termux/files/usr/bin/bash

exec aria2c \
    --enable-rpc \
    --save-session=$HOME/.aria2/aria2.session \
    --input-file=$HOME/.aria2/aria2.session \
    --save-session-interval=60 \
    --continue=true
