#!/data/data/com.termux/files/usr/bin/bash

export DISPLAY=:1

# start VNC ONLY if not running
pgrep Xvnc > /dev/null || vncserver :1 -geometry 1280x720 -depth 16

# start desktop session
exec openbox
exec tint2