#!/data/data/com.termux/files/usr/bin/bash

# Load .env file if it exists
ENV_FILE="$HOME/xelios-setup/services/tg-bot/.env"
if [ -f "$ENV_FILE" ]; then
    export $(cat "$ENV_FILE" | xargs)
fi

ENV_FILE="$HOME/xelios-setup/services/tg-downloader/.env"
if [ -f "$ENV_FILE" ]; then
    export $(cat "$ENV_FILE" | xargs)
fi

exec python3 "$HOME/xelios-setup/services/tg-bot/bot.py" >> ~/logs/tg-bot.log 2>&1
